export const TAURI_MIGRATION_CHANNEL_TO_COMMAND = {
  "window:minimize": "window_minimize",
  "window:maximize": "window_maximize",
  "window:close": "window_close",
  "get-system-platform": "get_system_platform",
  "get-system-debug-info": "get_system_debug_info",
  "get-app-version": "get_app_version",
  "nodejs-status": "nodejs_status",
  "select-node-folder": "select_node_folder",
  "get-node-path": "get_node_path",
  "get-user-settings": "get_user_settings",
  "set-user-settings": "set_user_settings",
  "select-app-folder": "select_app_folder",
  "select-app-location": "select_app_location",
  "check-ai-rules": "check_ai_rules",
  "get-templates": "get_templates",
  "read-app-file": "read_app_file",
  "edit-app-file": "edit_app_file",
  "search-app-files": "search_app_files",
  "list-versions": "list_versions",
  "get-current-branch": "get_current_branch",
  "run-app": "run_app",
  "stop-app": "stop_app",
  "restart-app": "restart_app",
  "respond-to-app-input": "respond_to_app_input",
  "chat:stream": "chat_stream",
  "chat:cancel": "chat_cancel",
  "agent-tool:get-tools": "agent_tool_get_tools",
  "agent-tool:set-consent": "agent_tool_set_consent",
  "agent-tool:consent-response": "agent_tool_consent_response",
  "mcp:list-servers": "mcp_list_servers",
  "mcp:create-server": "mcp_create_server",
  "mcp:update-server": "mcp_update_server",
  "mcp:delete-server": "mcp_delete_server",
  "mcp:list-tools": "mcp_list_tools",
  "mcp:get-tool-consents": "mcp_get_tool_consents",
  "mcp:set-tool-consent": "mcp_set_tool_consent",
  "mcp:tool-consent-response": "mcp_tool_consent_response",
  "vercel:save-token": "vercel_save_token",
  "vercel:list-projects": "vercel_list_projects",
  "vercel:is-project-available": "vercel_is_project_available",
  "local-models:list-ollama": "local_models_list_ollama",
  "local-models:list-lmstudio": "local_models_list_lmstudio",
  "get-themes": "get_themes",
  "generate-theme-prompt": "generate_theme_prompt",
  "generate-theme-from-url": "generate_theme_from_url",
  "save-theme-image": "save_theme_image",
  "cleanup-theme-images": "cleanup_theme_images",
  "apply-visual-editing-changes": "apply_visual_editing_changes",
  "analyze-component": "analyze_component",
  "check-problems": "check_problems",
  "show-item-in-folder": "show_item_in_folder",
  "clear-session-data": "clear_session_data",
  "reset-all": "reset_all",
  "reload-env-path": "reload_env_path",
  "does-release-note-exist": "does_release_note_exist",
  "get-user-budget": "get_user_budget",
  "upload-to-signed-url": "upload_to_signed_url",
  "restart-dyad": "restart_dyad",
  "add-log": "add_log",
  "clear-logs": "clear_logs",
  "open-external-url": "open_external_url",
  "leptos:render-route": "leptos_render_route",
} as const;

export const TAURI_MIGRATION_INVOKE_CHANNELS = Object.keys(
  TAURI_MIGRATION_CHANNEL_TO_COMMAND,
);

export const TAURI_MIGRATION_EVENT_CHANNELS = [
  "telemetry:event",
  "force-close-detected",
  "app:output",
  "chat:stream:start",
  "chat:stream:end",
  "chat:response:chunk",
  "chat:response:end",
  "chat:response:error",
  "agent-tool:consent-request",
  "agent-tool:todos-update",
  "agent-tool:problems-update",
  "mcp:tool-consent-request",
] as const;

export function isTauriMigrationInvokeChannel(
  channel: string,
): channel is keyof typeof TAURI_MIGRATION_CHANNEL_TO_COMMAND {
  return channel in TAURI_MIGRATION_CHANNEL_TO_COMMAND;
}

export function isTauriMigrationEventChannel(channel: string): boolean {
  return (TAURI_MIGRATION_EVENT_CHANNELS as readonly string[]).includes(
    channel,
  );
}
