export const TAURI_MIGRATION_CHANNEL_TO_COMMAND = {
  "window:minimize": "window_minimize",
  "window:maximize": "window_maximize",
  "window:close": "window_close",
  "get-system-platform": "get_system_platform",
  "get-system-debug-info": "get_system_debug_info",
  "get-app-version": "get_app_version",
  "get-env-vars": "get_env_vars",
  "get-app-env-vars": "get_app_env_vars",
  "set-app-env-vars": "set_app_env_vars",
  "get-context-paths": "get_context_paths",
  "set-context-paths": "set_context_paths",
  "get-proposal": "get_proposal",
  "reject-proposal": "reject_proposal",
  "free-agent-quota:get-status": "free_agent_quota_get_status",
  "is-capacitor": "is_capacitor",
  "sync-capacitor": "sync_capacitor",
  "open-ios": "open_ios",
  "open-android": "open_android",
  "import-app": "import_app",
  "get-app-upgrades": "get_app_upgrades",
  "execute-app-upgrade": "execute_app_upgrade",
  "create-app": "create_app",
  "get-app": "get_app",
  "list-apps": "list_apps",
  "search-app": "search_app",
  "delete-app": "delete_app",
  "copy-app": "copy_app",
  "rename-app": "rename_app",
  "get-chat": "get_chat",
  "get-chats": "get_chats",
  "create-chat": "create_chat",
  "update-chat": "update_chat",
  "delete-chat": "delete_chat",
  "delete-messages": "delete_messages",
  "search-chats": "search_chats",
  "nodejs-status": "nodejs_status",
  "select-node-folder": "select_node_folder",
  "get-node-path": "get_node_path",
  "get-user-settings": "get_user_settings",
  "set-user-settings": "set_user_settings",
  "get-latest-security-review": "get_latest_security_review",
  "select-app-folder": "select_app_folder",
  "select-app-location": "select_app_location",
  "check-ai-rules": "check_ai_rules",
  "check-app-name": "check_app_name",
  "get-templates": "get_templates",
  "read-app-file": "read_app_file",
  "edit-app-file": "edit_app_file",
  "search-app-files": "search_app_files",
  "change-app-location": "change_app_location",
  "list-versions": "list_versions",
  "checkout-version": "checkout_version",
  "get-current-branch": "get_current_branch",
  "rename-branch": "rename_branch",
  "run-app": "run_app",
  "stop-app": "stop_app",
  "restart-app": "restart_app",
  "respond-to-app-input": "respond_to_app_input",
  "chat:stream": "chat_stream",
  "chat:cancel": "chat_cancel",
  "chat:count-tokens": "chat_count_tokens",
  "chat:add-dep": "chat_add_dep",
  "agent-tool:get-tools": "agent_tool_get_tools",
  "agent-tool:set-consent": "agent_tool_set_consent",
  "agent-tool:consent-response": "agent_tool_consent_response",
  "mcp:list-servers": "mcp_list_servers",
  "mcp:create-server": "mcp_create_server",
  "mcp:update-server": "mcp_update_server",
  "mcp:delete-server": "mcp_delete_server",
  "mcp:list-tools": "mcp_list_tools",
  "mcp:get-tool-consents": "mcp_get_tool_consents",
  "mcp:set-tool-consent": "mcp_set_tool_consent",
  "mcp:tool-consent-response": "mcp_tool_consent_response",
  "vercel:save-token": "vercel_save_token",
  "vercel:list-projects": "vercel_list_projects",
  "vercel:is-project-available": "vercel_is_project_available",
  "vercel:create-project": "vercel_create_project",
  "vercel:connect-existing-project": "vercel_connect_existing_project",
  "vercel:get-deployments": "vercel_get_deployments",
  "vercel:disconnect": "vercel_disconnect",
  "get-language-model-providers": "get_language_model_providers",
  "get-language-models": "get_language_models",
  "get-language-models-by-providers": "get_language_models_by_providers",
  "create-custom-language-model-provider":
    "create_custom_language_model_provider",
  "edit-custom-language-model-provider": "edit_custom_language_model_provider",
  "delete-custom-language-model-provider":
    "delete_custom_language_model_provider",
  "create-custom-language-model": "create_custom_language_model",
  "delete-custom-language-model": "delete_custom_language_model",
  "delete-custom-model": "delete_custom_model",
  "supabase:list-organizations": "supabase_list_organizations",
  "supabase:delete-organization": "supabase_delete_organization",
  "supabase:list-all-projects": "supabase_list_all_projects",
  "supabase:list-branches": "supabase_list_branches",
  "supabase:get-edge-logs": "supabase_get_edge_logs",
  "supabase:set-app-project": "supabase_set_app_project",
  "supabase:unset-app-project": "supabase_unset_app_project",
  "supabase:fake-connect-and-set-project":
    "supabase_fake_connect_and_set_project",
  "neon:create-project": "neon_create_project",
  "neon:get-project": "neon_get_project",
  "neon:fake-connect": "neon_fake_connect",
  "local-models:list-ollama": "local_models_list_ollama",
  "local-models:list-lmstudio": "local_models_list_lmstudio",
  "get-themes": "get_themes",
  "set-app-theme": "set_app_theme",
  "get-app-theme": "get_app_theme",
  "get-custom-themes": "get_custom_themes",
  "create-custom-theme": "create_custom_theme",
  "update-custom-theme": "update_custom_theme",
  "delete-custom-theme": "delete_custom_theme",
  "prompts:list": "prompts_list",
  "prompts:create": "prompts_create",
  "prompts:update": "prompts_update",
  "prompts:delete": "prompts_delete",
  "generate-theme-prompt": "generate_theme_prompt",
  "generate-theme-from-url": "generate_theme_from_url",
  "save-theme-image": "save_theme_image",
  "cleanup-theme-images": "cleanup_theme_images",
  "apply-visual-editing-changes": "apply_visual_editing_changes",
  "analyze-component": "analyze_component",
  "check-problems": "check_problems",
  "show-item-in-folder": "show_item_in_folder",
  "clear-session-data": "clear_session_data",
  "reset-all": "reset_all",
  "reload-env-path": "reload_env_path",
  "does-release-note-exist": "does_release_note_exist",
  "get-user-budget": "get_user_budget",
  "upload-to-signed-url": "upload_to_signed_url",
  "restart-dyad": "restart_dyad",
  "add-to-favorite": "add_to_favorite",
  "update-app-commands": "update_app_commands",
  "plan:create": "plan_create",
  "plan:get": "plan_get",
  "plan:get-for-chat": "plan_get_for_chat",
  "plan:update-plan": "plan_update",
  "plan:delete": "plan_delete",
  "github:start-flow": "github_start_flow",
  "github:list-repos": "github_list_repos",
  "github:get-repo-branches": "github_get_repo_branches",
  "github:is-repo-available": "github_is_repo_available",
  "github:create-repo": "github_create_repo",
  "github:connect-existing-repo": "github_connect_existing_repo",
  "github:push": "github_push",
  "github:fetch": "github_fetch",
  "github:pull": "github_pull",
  "github:rebase": "github_rebase",
  "github:rebase-abort": "github_rebase_abort",
  "github:merge-abort": "github_merge_abort",
  "github:rebase-continue": "github_rebase_continue",
  "github:create-branch": "github_create_branch",
  "github:switch-branch": "github_switch_branch",
  "github:delete-branch": "github_delete_branch",
  "github:rename-branch": "github_rename_branch",
  "github:merge-branch": "github_merge_branch",
  "github:list-local-branches": "github_list_local_branches",
  "github:list-remote-branches": "github_list_remote_branches",
  "github:get-conflicts": "github_get_conflicts",
  "github:get-git-state": "github_get_git_state",
  "github:list-collaborators": "github_list_collaborators",
  "github:invite-collaborator": "github_invite_collaborator",
  "github:remove-collaborator": "github_remove_collaborator",
  "github:clone-repo-from-url": "github_clone_repo_from_url",
  "github:disconnect": "github_disconnect",
  "git:get-uncommitted-files": "git_get_uncommitted_files",
  "git:commit-changes": "git_commit_changes",
  "add-log": "add_log",
  "clear-logs": "clear_logs",
  "open-external-url": "open_external_url",
  "leptos:render-route": "leptos_render_route",
} as const;

export const TAURI_MIGRATION_INVOKE_CHANNELS = Object.keys(
  TAURI_MIGRATION_CHANNEL_TO_COMMAND,
);

export const TAURI_MIGRATION_EVENT_CHANNELS = [
  "telemetry:event",
  "force-close-detected",
  "app:output",
  "deep-link-received",
  "chat:stream:start",
  "chat:stream:end",
  "chat:response:chunk",
  "chat:response:end",
  "chat:response:error",
  "help:chat:response:chunk",
  "help:chat:response:end",
  "help:chat:response:error",
  "agent-tool:consent-request",
  "agent-tool:todos-update",
  "agent-tool:problems-update",
  "mcp:tool-consent-request",
  "github:flow-update",
  "github:flow-success",
  "github:flow-error",
  "plan:update",
  "plan:exit",
  "plan:questionnaire",
] as const;

export function isTauriMigrationInvokeChannel(
  channel: string,
): channel is keyof typeof TAURI_MIGRATION_CHANNEL_TO_COMMAND {
  return channel in TAURI_MIGRATION_CHANNEL_TO_COMMAND;
}

export function isTauriMigrationEventChannel(channel: string): boolean {
  return (TAURI_MIGRATION_EVENT_CHANNELS as readonly string[]).includes(
    channel,
  );
}
